package Telas;
import Conexao.Conexao;
import Dados.WebServiceCep;
import Dados.clProfessores;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Thiago
 */
public class CadastroProfessores extends javax.swing.JFrame {

 
    clProfessores objPro = new clProfessores();
    Conexao conex = new Conexao();
    int flag = 0;
    
    public CadastroProfessores() {
        initComponents();        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagens/iconeProfessor.png")));  
        comboBoxes();
        carregaGrid();
        modeloTabela();
    }
    
    public void carregaGrid() {
        objPro.PesquisaProfessores(grdProfessores);
    }
    
    public void comboBoxes()
    {
        cbxEstadoCivil.addItem("Selecione");
        cbxEstadoCivil.addItem("Solteiro(a)");
        cbxEstadoCivil.addItem("Casado(a)");
        cbxEstadoCivil.addItem("Divorciado(a)");
        cbxEstadoCivil.addItem("Viuvo(a)");
        
        cbxSexo.addItem("Selecione");
        cbxSexo.addItem("Masculino");
        cbxSexo.addItem("Feminino");
        
        cbxStatus.addItem("Selecione");
        cbxStatus.addItem("Ativo");
        cbxStatus.addItem("Inativo");
        
        
        cbxEstados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "AC", "AL", "AM", "AP", "BA", 
                                                                                             "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", 
                                                                                             "PI", "PR", "RJ", "RN", "RO", "RS", "SC", "SE", "SP", "TO" }));
    }
    
        public void buscaCep() {
        //Faz a busca para o cep 58043-280
        WebServiceCep webServiceCep = WebServiceCep.searchCep(txtFCep.getText());
        //A ferramenta de busca ignora qualquer caracter que n?o seja n?mero.

        //caso a busca ocorra bem, imprime os resultados.
        if (webServiceCep.wasSuccessful()) {
            txtEndereco.setText(webServiceCep.getLogradouroFull());
            txtCidade.setText(webServiceCep.getCidade());
            txtBairro.setText(webServiceCep.getBairro());
            cbxEstados.setSelectedItem(webServiceCep.getUf());

        } 
        if (txtFCep.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CEP para continuar!", "Atenção", JOptionPane.INFORMATION_MESSAGE); 
        }
        
        else {
            JOptionPane.showMessageDialog(null, "CEP não encontrado!", "Atenção", JOptionPane.ERROR_MESSAGE);
        }
        
    }
        
            public void modeloTabela() {  
        grdProfessores.getColumnModel().getColumn(0).setPreferredWidth(30);
        grdProfessores.getColumnModel().getColumn(0).setResizable(false);
        grdProfessores.getColumnModel().getColumn(1).setPreferredWidth(110);
        grdProfessores.getColumnModel().getColumn(1).setResizable(false);
        grdProfessores.getColumnModel().getColumn(2).setPreferredWidth(75);
        grdProfessores.getColumnModel().getColumn(2).setResizable(false);
        grdProfessores.getColumnModel().getColumn(3).setPreferredWidth(100);
        grdProfessores.getColumnModel().getColumn(3).setResizable(false);
        grdProfessores.getColumnModel().getColumn(4).setPreferredWidth(100);
        grdProfessores.getColumnModel().getColumn(4).setResizable(false);
        grdProfessores.getColumnModel().getColumn(5).setPreferredWidth(100);
        grdProfessores.getColumnModel().getColumn(5).setResizable(false); 
        grdProfessores.getColumnModel().getColumn(6).setPreferredWidth(100);
        grdProfessores.getColumnModel().getColumn(6).setResizable(false);  
        grdProfessores.getTableHeader().setReorderingAllowed(false);
        grdProfessores.setAutoResizeMode(grdProfessores.AUTO_RESIZE_OFF);
        grdProfessores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtFTel = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFCel = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtFCep = new javax.swing.JFormattedTextField();
        btnNovo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFRG = new javax.swing.JFormattedTextField();
        txtFCpf = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxEstadoCivil = new javax.swing.JComboBox<>();
        cbxSexo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        txtFNasc = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtFAdmissao = new javax.swing.JFormattedTextField();
        txtCTPS = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtInstrucao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdProfessores = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxEstados = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cbSim = new javax.swing.JCheckBox();
        cbNao = new javax.swing.JCheckBox();
        btnBuscaCep = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        cbxStatus = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnLocalizar = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de Professores");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Endereço *");

        txtEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtEndereco.setEnabled(false);

        txtFTel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        try {
            txtFTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFTel.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Bairro");

        txtFCel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        try {
            txtFCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFCel.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("CEP");

        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtEmail.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Cidade");

        txtCidade.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtCidade.setEnabled(false);

        txtBairro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtBairro.setEnabled(false);

        txtFCep.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        try {
            txtFCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFCep.setEnabled(false);

        btnNovo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Adicionar.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("ID");

        txtCod.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtCod.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("RG *");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("CPF *");

        txtFRG.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        try {
            txtFRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFRG.setText("");
        txtFRG.setEnabled(false);

        txtFCpf.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        try {
            txtFCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFCpf.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Estado civil *");

        cbxEstadoCivil.setEnabled(false);

        cbxSexo.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Sexo *");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Celular");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Telefone");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nome *");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("E-mail");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Nascimento");

        btnSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtFNasc.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        try {
            txtFNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFNasc.setEnabled(false);

        txtNome.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtNome.setEnabled(false);

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Admissão");

        txtFAdmissao.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        try {
            txtFAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFAdmissao.setEnabled(false);

        txtCTPS.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtCTPS.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("Nº CTPS *");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setText("Instrução");

        txtInstrucao.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtInstrucao.setEnabled(false);

        grdProfessores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Nascimento", "Telefone", "Celular", "Nº CTPS", "E-maill", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grdProfessores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdProfessoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grdProfessores);
        if (grdProfessores.getColumnModel().getColumnCount() > 0) {
            grdProfessores.getColumnModel().getColumn(0).setResizable(false);
            grdProfessores.getColumnModel().getColumn(1).setResizable(false);
            grdProfessores.getColumnModel().getColumn(2).setResizable(false);
            grdProfessores.getColumnModel().getColumn(3).setResizable(false);
            grdProfessores.getColumnModel().getColumn(4).setResizable(false);
            grdProfessores.getColumnModel().getColumn(5).setResizable(false);
            grdProfessores.getColumnModel().getColumn(6).setResizable(false);
            grdProfessores.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Nº");

        txtNumero.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtNumero.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("Estado");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Campos obrigatórios *");

        cbxEstados.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Complemento");

        txtComplemento.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtComplemento.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Possui internet?", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        buttonGroup1.add(cbSim);
        cbSim.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbSim.setText("Sim");
        cbSim.setEnabled(false);
        cbSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSimActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbNao);
        cbNao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbNao.setText("Não");
        cbNao.setEnabled(false);
        cbNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNaoActionPerformed(evt);
            }
        });

        btnBuscaCep.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBuscaCep.setText("Buscar CEP");
        btnBuscaCep.setEnabled(false);
        btnBuscaCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbSim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbNao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscaCep)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSim)
                    .addComponent(cbNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscaCep))
        );

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setText("Status *");

        cbxStatus.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        btnLocalizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLocalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        btnLocalizar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLocalizar, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
            .addComponent(txtPesquisa)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnLocalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnExcluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel7)
                                .addGap(152, 152, 152)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtFNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel4)))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtFRG, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addComponent(jLabel12)
                            .addComponent(jLabel6)
                            .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(214, 214, 214)
                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel23)
                                            .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(cbxEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(txtFAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(txtCTPS, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel20)))
                                .addGap(22, 22, 22)
                                .addComponent(jLabel21))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFTel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(txtFCel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addComponent(jLabel18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtFCep, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel11))
                            .addComponent(jLabel23))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel22)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCTPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Utilidades clUtilidades = new Utilidades();
        //clUtilidades.fecharForm();
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        //Principal tPrincipal = new Principal();
        //tPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void cbSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSimActionPerformed
        if (cbSim.isSelected() == true) {
            txtFCep.setEnabled(true);
            txtNumero.setEnabled(true);
            txtEndereco.setEnabled(false);
            txtBairro.setEnabled(false);
            txtNumero.setEnabled(false);
            txtCidade.setEnabled(false);
            cbxEstados.setEnabled(false);
            txtNumero.setEnabled(true);
            btnBuscaCep.setEnabled(true);
            txtFCep.requestFocus();
           
        }
    }//GEN-LAST:event_cbSimActionPerformed

    private void cbNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNaoActionPerformed
        if (cbNao.isSelected() == true) {
            txtEndereco.setEnabled(true);
            txtBairro.setEnabled(true);
            txtNumero.setEnabled(true);
            txtCidade.setEnabled(true);
            cbxEstados.setEnabled(true);
            txtFCep.setEnabled(true);
            btnBuscaCep.setEnabled(false);
          
        }
    }//GEN-LAST:event_cbNaoActionPerformed

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        if (txtPesquisa.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Não deixe o campo de pesquisa vazio!", "Erro", JOptionPane.ERROR_MESSAGE);
            carregaGrid();  
        }
        else {
            objPro.PesquisaProfessor(txtPesquisa.getText(), grdProfessores);
        }
        
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtNome.getText().isEmpty()) {
            String mN = "<html> Informe o <b>NOME</b> do professor! </html>";
            JLabel label = new JLabel(mN);
            label.setFont(new Font("Arial", Font.PLAIN, 12)); 
           JOptionPane.showMessageDialog(null, label, "Atenção", JOptionPane.INFORMATION_MESSAGE);
            txtNome.requestFocus();
        }
        
        else if (txtFRG.getText().equals("  .   .   - ")) {
            String mN = "<html> Informe o <b>RG</b> do professor! </html>";   
            JLabel label = new JLabel(mN);
            label.setFont(new Font("Arial", Font.PLAIN, 12)); 
            JOptionPane.showMessageDialog(null, label, "Atenção", JOptionPane.INFORMATION_MESSAGE);
            txtFRG.requestFocus();
        }        
        
        else if (txtFCpf.getText().equals("   .   .   .  ")) {
            String mN = "<html> Informe o <b>CPF</b> do professor! </html>";
            JLabel label = new JLabel(mN);
            label.setFont(new Font("Arial", Font.PLAIN, 12));  
            JOptionPane.showMessageDialog(null, label , "Atenção", JOptionPane.INFORMATION_MESSAGE);
            txtFCpf.requestFocus();
        }
        
        else if (cbxSexo.getSelectedItem().equals("Selecione")) {
            String mN = "<html> Informe o <b>GÊNERO</b> do professor! </html>";  
            JLabel label = new JLabel(mN);
            label.setFont(new Font("Arial", Font.PLAIN, 12));  
            JOptionPane.showMessageDialog(null, label, "Atenção", JOptionPane.INFORMATION_MESSAGE);
            cbxSexo.requestFocus();
        }
        
        else if (cbxEstadoCivil.getSelectedItem().equals("Selecione")) {
            String mN = "<html> Informe o <b>ESTADO CIVIL</b> do professor! </html>";  
            JLabel label = new JLabel(mN);
            label.setFont(new Font("Arial", Font.PLAIN, 12));  
            JOptionPane.showMessageDialog(null, label, "Atenção", JOptionPane.INFORMATION_MESSAGE);
            cbxEstadoCivil.requestFocus();
        }
        
        else if (cbxStatus.getSelectedItem().equals("Selecione")) {
            String mN = "<html> Informe o <b>STATUS</b> do professor! </html>";
            JLabel label = new JLabel(mN);
            label.setFont(new Font("Arial", Font.PLAIN, 12));  
            JOptionPane.showMessageDialog(null, label, "Atenção", JOptionPane.INFORMATION_MESSAGE);
            cbxStatus.requestFocus();
        }
        
        
        
        else {
            if (flag == 1) {
                objPro.setNome(txtNome.getText());
                objPro.setRg(txtFRG.getText());
                objPro.setCpf(txtFCpf.getText());
                objPro.setSexo(cbxSexo.getSelectedItem().toString());
                objPro.setEstadocivil(cbxEstadoCivil.getSelectedItem().toString());
                objPro.setEndereco(txtEndereco.getText());
                objPro.setNumeroendereco(Integer.parseInt(txtNumero.getText()));
                objPro.setBairro(txtBairro.getText());
                objPro.setCidade(txtCidade.getText());
                objPro.setEstado(cbxEstados.getSelectedItem().toString());
                objPro.setCep(txtFCep.getText());
                objPro.setComplemento(txtComplemento.getText());
                objPro.setNctps(txtCTPS.getText());
                objPro.setInstrucao(txtInstrucao.getText());
                objPro.setStatus(cbxStatus.getSelectedItem().toString());
                objPro.setNascimento(txtFNasc.getText());
                objPro.setAdmissao(txtFAdmissao.getText());
                objPro.setTelefone(txtFTel.getText());
                objPro.setCelular(txtFCel.getText());
                objPro.setEmail(txtEmail.getText());
                objPro.Salvar();
                btnSalvar.setEnabled(false);
                carregaGrid();
                txtNome.setText("");
                txtFRG.setText("");
                txtFCep.setText("");
                txtFNasc.setText("");
                cbxSexo.setSelectedItem("Selecione");
                cbxEstadoCivil.setSelectedItem("Selecione");
                txtEndereco.setText("");
                txtNumero.setText("");
                txtBairro.setText("");
                txtCidade.setText("");
                cbxEstados.setSelectedItem("Selecione");
                txtFCep.setText("");
                txtComplemento.setText("");
                txtFAdmissao.setText("");
                txtCTPS.setText("");
                txtInstrucao.setText("");
                txtFTel.setText("");
                txtFCel.setText("");
                cbxStatus.setSelectedItem("Selecione");   
                txtEmail.setText("");
                txtFCpf.setText("");   
            }
 
        }
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnBuscaCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCepActionPerformed
        if (txtFCep.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o CEP que deseja pesquisar!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            buscaCep();
        }
    }//GEN-LAST:event_btnBuscaCepActionPerformed

    private void grdProfessoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdProfessoresMouseClicked
        String codigoProfessor = "" + grdProfessores.getValueAt(grdProfessores.getSelectedRow(), 0);
        conex.Conectar();
        conex.executaSQL("SELECT *        " + 
                   "FROM PROFESSORES      " +
                   "WHERE CODPROFESSOR = '" + (codigoProfessor) + "'" 
                  );
        try {
            conex.resultado.next();   
            txtCod.setText(String.valueOf(conex.resultado.getObject("CODPROFESSOR").toString()));
            txtNome.setText(String.valueOf(conex.resultado.getObject("NOME")));
            txtFRG.setText(String.valueOf(conex.resultado.getObject("RG")));
            txtFCpf.setText(String.valueOf(conex.resultado.getObject("CPF")));
            cbxSexo.setSelectedItem(String.valueOf(conex.resultado.getObject("SEXO")));
            cbxEstadoCivil.setSelectedItem(String.valueOf(conex.resultado.getObject("ESTADOCIVIL")));
            txtEndereco.setText(String.valueOf(conex.resultado.getObject("ENDERECO")));
            txtNumero.setText(String.valueOf(conex.resultado.getObject("NUMENDERECO")));
            txtBairro.setText(String.valueOf(conex.resultado.getObject("BAIRRO")));
            txtCidade.setText(String.valueOf(conex.resultado.getObject("CIDADE")));
            txtFCep.setText(String.valueOf(conex.resultado.getObject("CEP")));
            txtComplemento.setText(String.valueOf(conex.resultado.getObject("COMPLEMENTO")));
            txtCTPS.setText(String.valueOf(conex.resultado.getObject("NCTPS")));
            txtInstrucao.setText(String.valueOf(conex.resultado.getObject("INSTRUCAO")));
            cbxStatus.setSelectedItem(String.valueOf(conex.resultado.getObject("STATUS")));   
            txtFNasc.setText(String.valueOf(conex.resultado.getObject("NASCIMENTO")).replace(".", "/"));
            txtFAdmissao.setText(String.valueOf(conex.resultado.getObject("ADMISSAO")).replace(".", "/"));
            txtFTel.setText(String.valueOf(conex.resultado.getObject("TELEFONE")));
            txtFCel.setText(String.valueOf(conex.resultado.getObject("CELULAR")));
            cbxEstados.setSelectedItem(String.valueOf(conex.resultado.getObject("ESTADO")));     
            txtEmail.setText(String.valueOf(conex.resultado.getObject("EMAIL")));
            
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar dados! \n" + ex);
        }       
        btnNovo.setEnabled(false);
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnSalvar.setEnabled(false);
        txtEmail.setEnabled(false);
        txtNome.setEnabled(false);
        btnSalvar.setEnabled(false); 
        btnExcluir.setEnabled(true);
        conex.DesconectaDB();
    }//GEN-LAST:event_grdProfessoresMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnSalvar.setEnabled(false);
        btnNovo.setEnabled(true);
        txtEmail.setEnabled(false);
        txtNome.setEnabled(false);
        btnSalvar.setEnabled(false); 
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        objPro.PesquisaProfessores(grdProfessores);
        //Desabilita os campos/botoes
        txtNome.setEnabled(false);
        txtFRG.setEnabled(false);
        txtFCpf.setEnabled(false);
        txtFCep.setEnabled(false);
        txtBairro.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNumero.setEnabled(false);
        txtComplemento.setEnabled(false);
        txtCTPS.setEnabled(false);
        txtFTel.setEnabled(false);
        txtCidade.setEnabled(false);
        txtFAdmissao.setEnabled(false);
        txtFNasc.setEnabled(false);
        cbxEstadoCivil.setEnabled(false);
        cbxEstados.setEnabled(false);
        cbxStatus.setEnabled(false);
        cbxSexo.setEnabled(false);
        txtEmail.setEnabled(false);
        txtInstrucao.setEnabled(false);
        cbSim.setEnabled(false);
        cbNao.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        flag = 1;
        btnSalvar.setEnabled(true);
        //Limpa todos os campos
        txtNome.setText("");
        txtFRG.setText("");
        txtFCep.setText("");
        txtFNasc.setText("");
        cbxSexo.setSelectedItem("Selecione");
        cbxEstadoCivil.setSelectedItem("Selecione");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        cbxEstados.setSelectedItem("Selecione");
        txtFCep.setText("");
        txtComplemento.setText("");
        txtFAdmissao.setText("");
        txtCTPS.setText("");
        txtInstrucao.setText("");
        txtFTel.setText("");
        txtFCel.setText("");
        cbxStatus.setSelectedItem("Selecione");   
        txtEmail.setText("");
        txtFCpf.setText("");
        btnNovo.setEnabled(false);
        //Habilita os campos para preencher
        txtNome.setEnabled(true);
        txtFRG.setEnabled(true);
        txtFCpf.setEnabled(true);
        txtFCep.setEnabled(true);
        txtBairro.setEnabled(true);
        txtEndereco.setEnabled(true);
        txtNumero.setEnabled(true);
        txtComplemento.setEnabled(true);
        txtCTPS.setEnabled(true);
        txtFTel.setEnabled(true);
        txtCidade.setEnabled(true);
        txtFAdmissao.setEnabled(true);
        txtFNasc.setEnabled(true);
        cbxEstadoCivil.setEnabled(true);
        cbxEstados.setEnabled(true);
        cbxStatus.setEnabled(true);
        cbxSexo.setEnabled(true);
        txtEmail.setEnabled(true);
        txtInstrucao.setEnabled(true);
        cbSim.setEnabled(true);
        cbNao.setEnabled(true);
        
    }//GEN-LAST:event_btnNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new CadastroProfessores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaCep;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbNao;
    private javax.swing.JCheckBox cbSim;
    private javax.swing.JComboBox<String> cbxEstadoCivil;
    private javax.swing.JComboBox<String> cbxEstados;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JComboBox<String> cbxStatus;
    private javax.swing.JTable grdProfessores;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCTPS;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JFormattedTextField txtFAdmissao;
    private javax.swing.JFormattedTextField txtFCel;
    private javax.swing.JFormattedTextField txtFCep;
    private javax.swing.JFormattedTextField txtFCpf;
    private javax.swing.JFormattedTextField txtFNasc;
    private javax.swing.JFormattedTextField txtFRG;
    private javax.swing.JFormattedTextField txtFTel;
    private javax.swing.JTextField txtInstrucao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
