import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rlteixeira-inf152
 */
public class Principal extends javax.swing.JFrame {
    
    //  Ultilidades
    Utilidades clUtilidades = new Utilidades();
    
    BufferedImage imagemFundo;
    
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagens/iconePrincipal.png")));
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHora = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMPrincipal = new javax.swing.JMenuBar();
        jCadastro = new javax.swing.JMenu();
        jCTurma = new javax.swing.JMenuItem();
        jCServico = new javax.swing.JMenuItem();
        jCAluno = new javax.swing.JMenuItem();
        jCProfessor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jCUsuario = new javax.swing.JMenuItem();
        jFinanceiro = new javax.swing.JMenu();
        jFGM = new javax.swing.JMenuItem();
        jFCR = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tela Principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblHora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagemFundoPrincipal.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));

        jCadastro.setText("Cadastro");

        jCTurma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jCTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeTurma.png"))); // NOI18N
        jCTurma.setText("Turma");
        jCTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTurmaActionPerformed(evt);
            }
        });
        jCadastro.add(jCTurma);

        jCServico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jCServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeAtividade.png"))); // NOI18N
        jCServico.setText("Serviço");
        jCServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCServicoActionPerformed(evt);
            }
        });
        jCadastro.add(jCServico);

        jCAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jCAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeAluno.png"))); // NOI18N
        jCAluno.setText("Aluno");
        jCAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCAlunoActionPerformed(evt);
            }
        });
        jCadastro.add(jCAluno);

        jCProfessor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jCProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeProfessor.png"))); // NOI18N
        jCProfessor.setText("Professor");
        jCProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCProfessorActionPerformed(evt);
            }
        });
        jCadastro.add(jCProfessor);
        jCadastro.add(jSeparator2);

        jCUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jCUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeUsuario.png"))); // NOI18N
        jCUsuario.setText("Usuário/Login");
        jCUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCUsuarioActionPerformed(evt);
            }
        });
        jCadastro.add(jCUsuario);

        jMPrincipal.add(jCadastro);

        jFinanceiro.setText("Financeiro");

        jFGM.setText("Gerar Mensalidade");
        jFinanceiro.add(jFGM);

        jFCR.setText("Contas a Receber");
        jFinanceiro.add(jFCR);

        jMPrincipal.add(jFinanceiro);

        setJMenuBar(jMPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       clUtilidades.fecharForm();
    }//GEN-LAST:event_formWindowClosing

    private void jCTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTurmaActionPerformed
       CadastroTurmas cTurmas = new CadastroTurmas();
       cTurmas.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jCTurmaActionPerformed

    private void jCServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCServicoActionPerformed
       CadastroAtividades cServico = new CadastroAtividades();
       cServico.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jCServicoActionPerformed

    private void jCAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCAlunoActionPerformed
        CadastroAlunos cAlunos = new CadastroAlunos();
        cAlunos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jCAlunoActionPerformed

    private void jCProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCProfessorActionPerformed
        CadastroProfessores cProfessores = new CadastroProfessores();
        cProfessores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jCProfessorActionPerformed

    private void jCUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCUsuarioActionPerformed
        CadastroUsuario cUsuario = new CadastroUsuario();
        cUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jCUsuarioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(NORMAL);  
        
        //Data
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        lblData.setText(formato.format(dataSistema));
        
        
        //Hora
        Timer timer = new Timer(1000, new hora());
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);              
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jCAluno;
    private javax.swing.JMenuItem jCProfessor;
    private javax.swing.JMenuItem jCServico;
    private javax.swing.JMenuItem jCTurma;
    private javax.swing.JMenuItem jCUsuario;
    private javax.swing.JMenu jCadastro;
    private javax.swing.JMenuItem jFCR;
    private javax.swing.JMenuItem jFGM;
    private javax.swing.JMenu jFinanceiro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMPrincipal;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHora;
    // End of variables declaration//GEN-END:variables

    class hora implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            lblHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
        
    }
    
    
    
    
    
}